Feature/support items filtering by tags
AOEpeople/aoe_technology_radar pull request #245
Opened 2022-11-11 17:51 UTC by onikiienko

Hi, guys!
I've added the possibility of filtering blips by tags from item metadata.

We are using your package to create our own tech radar in my company but we have too many streams(frontend, backend, are, etc) and products, it's really important to us to have all the blips in a single place. So, we've decided to add filtering. Hope you will enjoy it and merge.

I am giving you an example of using such filtering in a GIF file. It uses URL as a state, so you can easily share a link with someone or use it in company documentation, etc. As a plus, it works perfectly during the search.

So, please give any suggestions for these changes and I'll handle them.

Thanks

![2022-11-11 19 45 44](https://user-images.githubusercontent.com/3531246/201399656-588246c8-3793-4ded-9b02-2c6d2a023d13.gif)

2022-11-14 07:26 UTC, mathiasschopmans commented on src/components/App.tsx
> -  const data = useFetch<Data>(
How do we ensure that the client cache is invalidated now that the `REACT_APP_BUILDHASH` has been removed from the data files? :)

2022-11-14 09:43 UTC, bastianccm commented
Hi @onikiienko 

thank you so much! This is really awesome!

I'll get back to you with some feedback, in general it looks awesome!


Thanks, Basti

2022-11-14 10:37 UTC, bastianccm requested changes
Please add the build hash @mathiasschopmans mentioned back in, and have a look on the other two comments regarding fewer tags and `,` in tags, afterwards I'm happy to merge it.

Also, if possible, can you squash the commits together afterwards?

2022-11-14 10:37 UTC, bastianccm commented on src/components/TagsModal/TagsModal.tsx
> +          style={{ columns: Math.floor(tags.length / 8) }}
This breaks for small amounts of tags, if you have less than 8 it will round to `0`.
`Math.ceil` is probably better?

![image](https://user-images.githubusercontent.com/1145424/201637372-feb64aab-365d-422a-979f-c49c768599ba.png)

2022-11-14 10:37 UTC, bastianccm commented on src/hooks/use-search-param-state.tsx
> +  arrayFormat: "comma",
This breaks tags which include a `,`:
![image](https://user-images.githubusercontent.com/1145424/201638062-bb5a1d29-c9c3-42d7-891e-6f79711c705d.png)

Selecting `b,c` in the example turns on both `b` and `c`, but adds `b,c` to the URL. Clicking more than once will add it again (because it is not understood as selected).
Maybe URL-encoding the `,` would help?

2022-11-14 17:40 UTC, onikiienko commented on src/components/App.tsx
> -  const data = useFetch<Data>(
oops, sorry for that😅 I have to fetch the newest changes. Will rollback it

2022-11-14 17:41 UTC, onikiienko commented on src/components/TagsModal/TagsModal.tsx
> +          style={{ columns: Math.floor(tags.length / 8) }}
will fix it in the near future

2022-11-14 17:42 UTC, onikiienko commented on src/hooks/use-search-param-state.tsx
> +  arrayFormat: "comma",
I didn't expect it:) thanks for your advice will think about what to do with this case, I have a bit more time.

2022-11-14 21:23 UTC, onikiienko commented on src/components/App.tsx
> -  const data = useFetch<Data>(
✅ rolled back those changes

2022-11-14 21:23 UTC, onikiienko commented on src/components/TagsModal/TagsModal.tsx
> +          style={{ columns: Math.floor(tags.length / 8) }}
✅ used ceil, which works better. thanks for advice

2022-11-14 21:24 UTC, onikiienko commented on src/hooks/use-search-param-state.tsx
> +  arrayFormat: "comma",
✅ I've used pipe "|" instead of comma as query-select docs recommend.

2022-11-15 07:52 UTC, bastianccm approved these changes

2022-11-15 07:53 UTC, merged

2022-11-17 21:53 UTC, danielpoe commented
Really awesome - thanks for this.

I added a small feature wish here: https://github.com/AOEpeople/aoe_technology_radar/issues/259