feat: provide sitemap
AOEpeople/aoe_technology_radar pull request #288
Opened 2023-01-06 21:22 UTC by d-koppenhagen

closes #287

2023-01-07 09:30 UTC, bastianccm requested changes
Awesome, thank you so much 🙇 

I think it does not merge to the most recent version anymore, as we moved from yarn to npm. Do you mind rebasing on the current main branch?

2023-01-07 14:23 UTC, d-koppenhagen commented
@bastianccm you were right. I rebased it. Should be up-to-date now.

2023-01-09 07:45 UTC, bastianccm approved these changes

2023-01-09 07:45 UTC, merged

2023-01-09 07:46 UTC, bastianccm commented
Thank you very much! I'll bump some dependencies and check one open bug, and will release this feature in a new version in the next days.